name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd anon-bot
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install flake8
        
    - name: Lint with flake8
      run: |
        cd anon-bot
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Run tests
      run: |
        cd anon-bot
        # Проверяем наличие тестов перед запуском
        if [ -d "tests" ] && [ "$(ls -A tests)" ]; then
          pytest
        else
          echo "Тесты не найдены, пропускаем этот шаг"
        fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Show SSH key fingerprint
      run: |
        ssh-add -l
        
    - name: Add host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        
    - name: Test SSH connection
      run: |
        ssh -v ${{ secrets.USER }}@${{ secrets.HOST }} 'echo "SSH connection successful"'

    - name: Add .env file
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cat > ${{ secrets.DEPLOY_PATH }}/anon-bot/.env << 'EOF'
        DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
        EOF"
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} "chmod 600 ${{ secrets.DEPLOY_PATH }}/anon-bot/.env"

    - name: Deploy to production
      run: |
        rsync -avz --delete \
          --exclude '.git*' \
          --exclude 'tests' \
          --exclude '.github' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./anon-bot/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_PATH }}/anon-bot/

    - name: Deploy scripts
      run: |
        rsync -avz --delete \
          --exclude '.git*' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./scripts/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_PATH }}/scripts/

    - name: Update service configuration
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} "DEPLOY_PATH=${{ secrets.DEPLOY_PATH }} SERVICE_NAME=discord-bot PROJECT_DIR=anon-bot bash ${{ secrets.DEPLOY_PATH }}/scripts/update_service.sh"
        
    - name: Restart service
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'sudo /usr/bin/systemctl restart discord-bot' 